// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlhEIlTKp0zT5to6iMkwbTMZhK1_QwcuE',
    appId: '1:1091777494161:web:8d1043944e9f34e2451330',
    messagingSenderId: '1091777494161',
    projectId: 'appstock-2a19c',
    authDomain: 'appstock-2a19c.firebaseapp.com',
    storageBucket: 'appstock-2a19c.appspot.com',
    measurementId: 'G-YH3Q5JLWJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1FN6qR4IJSpYvU2Cah6WIKb-28LFeRhM',
    appId: '1:1091777494161:android:c5f6de47fedec6e1451330',
    messagingSenderId: '1091777494161',
    projectId: 'appstock-2a19c',
    storageBucket: 'appstock-2a19c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOS9YaaSbina3c_QFuG35e_FOl93EMJ5o',
    appId: '1:1091777494161:ios:8b08ee78c24e4ec0451330',
    messagingSenderId: '1091777494161',
    projectId: 'appstock-2a19c',
    storageBucket: 'appstock-2a19c.appspot.com',
    iosBundleId: 'com.example.appstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOS9YaaSbina3c_QFuG35e_FOl93EMJ5o',
    appId: '1:1091777494161:ios:fa59c46795f1b547451330',
    messagingSenderId: '1091777494161',
    projectId: 'appstock-2a19c',
    storageBucket: 'appstock-2a19c.appspot.com',
    iosBundleId: 'com.example.appstock.RunnerTests',
  );
}
